/**
 * Video background (MP4) E2E: load via the timeline «Фон» row, verify the
 * project state, and round-trip through project / KFN / MP4 exports.
 * The fixture (e2e/fixtures/bg-sample.mp4) is generated by the app's own
 * exporter — see e2e/make-bg-fixture.mjs.
 */
import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { makeWavBytes, readBytes, readProjectZip, getKfnImporter } from './helpers';
import { getAppState, loadAudioIntoRole, exportViaDialog } from './support';

const fixturePath = join(dirname(fileURLToPath(import.meta.url)), 'fixtures', 'bg-sample.mp4');
const fixtureBytes = new Uint8Array(readFileSync(fixturePath));

test.beforeEach(async ({ page }) => {
  await page.goto('/');
  // Load audio + the bg video through the real UI paths.
  await loadAudioIntoRole(page, 'minus', makeWavBytes(2));
  await expect
    .poll(async () => (await getAppState(page)).bufferDurationByRole.minus, { timeout: 30_000 })
    .toBeGreaterThan(0);
  await page.locator('[data-testid="track-head-background"]').click();
  await page.locator('[data-testid="input-bg-load-panel"]').setInputFiles({
    name: 'bg-sample.mp4',
    mimeType: 'video/mp4',
    buffer: Buffer.from(fixtureBytes),
  });
  await expect
    .poll(async () => (await getAppState(page)).bgType, { timeout: 10_000 })
    .toBe('video');
});

test('loading the bg video sets bgType=video + filename', async ({ page }) => {
  const state = await getAppState(page);
  expect(state.bgType).toBe('video');
  expect(state.bgVideoFileName).toBe('bg-sample.mp4');
});

test('filmstrip thumbnails are decoded and cached for the timeline bg row', async ({ page }) => {
  // The filmstrip builds asynchronously (offline WebCodecs decode, no
  // playback); poll the hook until the strip is ready.
  const strip = await page.waitForFunction(
    () => {
      const s = window.__bgFilmstrip && window.__bgFilmstrip();
      return !!s && s.count > 0;
    },
    undefined,
    { timeout: 30_000 },
  ).then((h) => h.evaluate(() => window.__bgFilmstrip()!));
  // 2s fixture + 2s sampling interval → at least 1 thumbnail.
  expect(strip.count).toBeGreaterThanOrEqual(1);
  expect(strip.intervalSec).toBeGreaterThanOrEqual(2);
});

test('preview canvas shows the video frame (not the fallback color)', async ({ page }) => {
  // The fixture's frames are solid RED (see make-bg-fixture.mjs); the app's
  // fallback bg is dark #0e0f1a. Sample the preview canvas center: while the
  // video is playing (t=0 here) it must be red-dominant — proving the <video>
  // sync + draw path works, not just the model.
  const px = await page.evaluate(async () => {
    await new Promise((r) => setTimeout(r, 500)); // let the RAF loop paint a few frames
    const src = document.querySelector<HTMLCanvasElement>('.preview-wrap canvas')!;
    const tmp = document.createElement('canvas');
    tmp.width = 1;
    tmp.height = 1;
    const tctx = tmp.getContext('2d')!;
    tctx.drawImage(src, src.width / 2, src.height / 2, 1, 1, 0, 0, 1, 1);
    const d = tctx.getImageData(0, 0, 1, 1).data;
    return { r: d[0], g: d[1], b: d[2] };
  });
  expect(px.r).toBeGreaterThan(150);
  expect(px.g).toBeLessThan(60);
  expect(px.b).toBeLessThan(60);
});

test('project export embeds the video as background-video.mp4', async ({ page }) => {
  const path = await exportViaDialog(page, 'tab-project');
  const { project } = readProjectZip(readBytes(path));
  expect(project.background.bgType).toBe('video');
  expect(project.background.bgVideoFileName).toBe('bg-sample.mp4');
  // Full byte-identical round-trip of the video entry.
  const { unzipSync } = await import('fflate');
  const unzipped = unzipSync(readBytes(path));
  expect(unzipped['background-video.mp4']).toBeDefined();
  expect(unzipped['background-video.mp4'].length).toBe(fixtureBytes.length);
});

test('KFN export embeds the video as a type=5 file with an ID=62 effect', async ({ page }) => {
  const path = await exportViaDialog(page, 'tab-kfn');
  const bytes = readBytes(path);
  const importFromKfn = await getKfnImporter();
  const result = importFromKfn(bytes);
  expect(result.project.tracks.filter((t: any) => t.type === 'text').length).toBe(1);
});

test('MP4 export with a video background renders (decode pipeline smoke)', async ({ page }) => {
  await page.locator('[data-testid="btn-export"]').click();
  await page.locator('[data-testid="select-quality"]').selectOption('360p');
  const downloadPromise = page.waitForEvent('download', { timeout: 120_000 });
  await page.locator('[data-testid="btn-start-export"]').click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toMatch(/\.mp4$/);
  const out = readBytes(await download.path());
  expect(out.length).toBeGreaterThan(10_000);
});
